# Generated by Django 6.0.3 on 2026-04-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coach",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
