# Generated by Django 6.0.3 on 2026-04-13 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitapi", "0002_coach_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membre",
            name="join_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
