# Generated by Django 6.0.3 on 2026-04-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitapi", "0003_alter_membre_join_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
