# Generated by Django 6.0.3 on 2026-04-30 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitapi", "0007_coachcertificate_coachreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="membre",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_membres",
                to="fitapi.coach",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="tier",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("advanced", "Advanced"),
                    ("full", "Full Options"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
    ]
