# Generated by Django 6.0.3 on 2026-05-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitapi", "0010_conversation_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
