# Generated by Django 6.0.3 on 2026-05-30 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitapi", "0013_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargilyCheckout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chargily_id",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("checkout_url", models.URLField(blank=True, null=True)),
                (
                    "chargily_method",
                    models.CharField(
                        choices=[
                            ("edahabia", "EDAHABIA (Algerie Poste)"),
                            ("cib", "CIB (SATIM)"),
                        ],
                        default="edahabia",
                        max_length=20,
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("fr", "French"), ("ar", "Arabic"), ("en", "English")],
                        default="fr",
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chargily_checkout",
                        to="fitapi.payment",
                    ),
                ),
            ],
        ),
    ]
