# Generated by Django 6.0.3 on 2026-05-31 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitapi", "0015_machinereport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coachreview",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
