

services:
  web:
    build: ./fittech
    command: gunicorn fittech.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - ./fittech:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./fittech/.env
    restart: always
  cron:
    build: ./fittech
    command: >
      sh -c "echo '0 0 * * * cd /app && python manage.py generate_daily_token >> /var/log/cron.log 2>&1' | crontab - && cron -f"
    volumes:
      - ./fittech:/app
    env_file:
      - ./fittech/.env
    restart: always
volumes:
  static_volume:
  media_volume:


