services:
  redis:
    image: redis:7-alpine
    restart: always

  web:
    build: ./fittech
    command: daphne -b 0.0.0.0 -p 8000 fittech.asgi:application
    volumes:
      - ./fittech:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./fittech/.env
    depends_on:
      - redis
    restart: always

  cron:
    build: ./fittech
    command: >
      sh -c "echo '0 0 * * * cd /app && python manage.py generate_daily_token >> /var/log/cron.log 2>&1' | crontab - && cron -f"
    volumes:
      - ./fittech:/app
    env_file:
      - ./fittech/.env
    depends_on:
      - redis
    restart: always

volumes:
  static_volume:
  media_volume:
